//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Соц_поддержка
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int id { get; set; }
        public string Surename { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public string Birthday { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
        public string Recording_date { get; set; }
        public string Recording_time { get; set; }
        public Nullable<int> id_Departament { get; set; }
    
        public virtual Departament Departament { get; set; }
    }
}
