//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Соц_поддержка
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.Departament = new HashSet<Departament>();
        }
    
        public int id { get; set; }
        public string Surename { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public Nullable<int> id_Gender { get; set; }
        public Nullable<int> id_Speciality { get; set; }
        public string Phone { get; set; }
        public string Birthday { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departament> Departament { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Speciality Speciality { get; set; }
    }
}
